# Generated by Django 2.2.1 on 2019-05-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IpModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipmodel',
            old_name='name',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='ipmodel',
            name='port',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
